version: '3.9'

services:
  postgres:
    container_name: daevit-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=daevit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - daevit-server-network


networks:
  daevit-server-network:
    name: daevit-server-network

