# Spring Boot configuration
spring:
  application:
    name: Daevit Server

  graphql:
    graphiql:
      enabled: true
    path: /api/v1/graphql

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daevit
    username: postgres
    password: postgres

# Database migration
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/daevit
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-missing-locations: true
    user: postgres
    password: postgres

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: false
#    properties:
#      hibernate:
#        format_sql: true

# Logger configuration
logging:
  level:
    org.springframework: info
    org.hibernate.stat: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# Server configuration
server:
  port: 8081 #set your port
  error:
    include-binding-errors: always
    include-message: always
